---
- name: Install JDK and JRE (Java)
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600  # one hour 
    name: "{{ pkgs }}"
    state: present
  vars:
    pkgs:
    - openjdk-11-jdk
    - default-jre